# --- Environment management guidelines ---
# To create & activate environment {name} from this file:
# (1) $ conda env create -f environment.yml
# (2) $ conda activate {name}
# To update dependencies in environment {name} from this file:
# $ conda env update --file environment.yml --prune

# To create ENV file from loaded dependencies:
# $ conda env export --from-history > ENV.yml
# For the most comprehensive listing, with versions:
# $ conda list -e > ENV.txt
# Then install by running:
# $ conda create -n <env-name> --file ENV.txt

# Remember to periodically update conda and brew:
# $ conda update -n base -c conda-forge conda
# $ brew update

name: data-tools
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.10
  - pip>=19.0
  - requests
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - bs4
  - python-dotenv   # secure API key retrieval
  - pydantic        # python data validation
  - openssl         # ensures pycurl and wptools are installed correctly
  - pycurl 
  # - ipython
  # - scikit-learn

  - pip:
    - jsonschema    # json data validation
    - wptools
    - cinemagoer
    - spotipy