# --- Environment management guidelines ---
# To create & activate environment {name} from this file:
# (1) $ conda env create -f environment.yml
# (2) $ conda activate {name}
# To update dependencies from this file:
# $ conda env update --file environment.yml --prune

# To create ENV file from loaded dependencies:
# $ conda env export --from-history > ENV.yml
# For the most comprehensive listing, with versions:
# $ conda list -e > ENV.txt
# Then install by running:
# $ conda create -n <env-name> --file ENV.txt

# Remember to periodically update conda and brew:
# $ conda update -n base -c conda-forge conda
# $ brew update

name: data-tools
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.10
  - pip>=19.0
  - requests
  - pandas
  # Data validation
  - pydantic        
  # Web scraping
  - bs4
  # ensures pycurl and wptools are installed correctly
  - openssl         
  - pycurl 
  # Secure API key retrieval
  - python-dotenv   
  # Optional dependencies
  - scipy
  - matplotlib
  - seaborn

  - pip:
    # Typing
    # run `mypy --install-types` to install missing stubs. Pandas' given below.
    - mypy
    - pandas-stubs
    # Testing
    - pytest
    # - pytest-doctestplus
    # Linting
    - flake8
    # JSON data validation
    - jsonschema   
    # API clients
    - wptools
    - cinemagoer
    - spotipy