# To create ENV file from loaded dependencies:
# $ conda env export --from-history > ENV.yml
# For the most comprehensive listing, with versions:
# $ conda list -e > ENV.txt
# Then install by running:
# $ conda create -n <env-name> --file ENV.txt

# To update {name} environment from existing environment.yml:
# $ conda env update --file environment.yml --prune

name: data-tools
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.10
  - pip>=19.0
  - requests
  - scipy
  - pandas
  - matplotlib
  - seaborn
# - scikit-learn
  - bs4

  - pip:
      - pycurl==7.45.2
      - wptools==0.4.17
      - cinemagoer
      - spotipy