name: release-documentation

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine version number
        id: version
        # run: echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install sphinx furo pydata-sphinx-theme numpydoc autodoc_pydantic
          pip install -r requirements.txt
          pip install --editable .

      - name: Sphinx build
        run: |
          sphinx-build -D version=${{ steps.version.outputs.version }} docs/source _build/${{ steps.version.outputs.version }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/${{ steps.version.outputs.RELEASE_VERSION }}
          force_orphan: true
